### ISSUE TITLE
Erro: IOE e EOF exception ao '1) Listar suas respostas'

### ISSUE THREAD

**Issue by GustavoLR548** [solid-titans/AEDs3#17]
Durante o processo de listagem de respostas de um determinado usuário, o programa jogou um IOE e EOF exception. A causa exata é algo que eu não consigo determinar exatamente, mas decidi abrir o 'Issue' para que todos fiquem sabendo do problema:

# Situação atual do banco de dados

* 4 usuários no banco de dados
* 2 deles tem perguntas registradas
    * Ambas as perguntas possuem respostas de usuários diferentes

# Como que eu cheguei nesse erro:

Ao registrar as respostas na primeira pergunta , nada de estranho ocorreu e inclusive eu consegui registrar respostas com diferentes usuários. O erro só se manifestou quando eu fui inserir respostas na segunda pergunta registrada: eu inseri a resposta, e quando fui listar, isso foi imprimido na tela:

# Saida do terminal
```java
java.io.EOFException
        at java.base/java.io.RandomAccessFile.readInt(RandomAccessFile.java:837)
        at menu.pergunta.indices.ListaIDs$Bloco.lerBloco(ListaIDs.java:231)
        at menu.pergunta.indices.ListaIDs.readP(ListaIDs.java:174)
        at menu.pergunta.indices.ListaIDs.read(ListaIDs.java:134)
        at menu.sistema.CrudAPI.getRespostaArrayUser(CrudAPI.java:499)
        at menu.resposta.RespostaAPI.listarRespostasDoUsuario(RespostaAPI.java:50)
        at menu.sistema.CrudAPI.verificarRequisicaoEmPergunta(CrudAPI.java:211)
        at menu.Menu.navegarPergunta(Menu.java:277)
        at menu.sistema.CrudAPI.verificarRequisicaoDoUsuario(CrudAPI.java:130)
        at menu.Menu.acessoGarantido(Menu.java:197)
        at menu.Menu.Inicio(Menu.java:96)
        at Main.main(Main.java:12)
java.io.IOException: Negative seek offset
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:589)
        at crud.Crud.read(Crud.java:95)
        at menu.sistema.CrudAPI.getRespostaArrayUser(CrudAPI.java:506)
        at menu.resposta.RespostaAPI.listarRespostasDoUsuario(RespostaAPI.java:50)
        at menu.sistema.CrudAPI.verificarRequisicaoEmPergunta(CrudAPI.java:211)
        at menu.Menu.navegarPergunta(Menu.java:277)
        at menu.sistema.CrudAPI.verificarRequisicaoDoUsuario(CrudAPI.java:130)
        at menu.Menu.acessoGarantido(Menu.java:197)
        at menu.Menu.Inicio(Menu.java:96)
        at Main.main(Main.java:12)
■■■■■■■■■■■■■■
■▒Respostas▒▒■
■■■■■■■■■■■■■■

Operação terminou com sucesso!

Pressione 'Enter' para continuar...
```

**Comment by GustavoLR548** [comment]
# Update

Ok, eu encontrei um erro na função 'getRespostaArrayUser' em ```menu/sistema/CrudAPI.java linha 525```, ele não estava acessando a ListaIDs correta e por isso dava esse erro. Porém algo o outro usuário agora está apresentando o mesmo erro

# Saida do terminal

```java
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at menu.pergunta.indices.ListaIDs.readP(ListaIDs.java:191)
        at menu.pergunta.indices.ListaIDs.read(ListaIDs.java:134)
        at menu.sistema.CrudAPI.getRespostaArrayUser(CrudAPI.java:498)
        at menu.resposta.RespostaAPI.listarRespostasDoUsuario(RespostaAPI.java:50)
        at menu.sistema.CrudAPI.verificarRequisicaoEmPergunta(CrudAPI.java:211)
        at menu.Menu.navegarPergunta(Menu.java:277)
        at menu.sistema.CrudAPI.verificarRequisicaoDoUsuario(CrudAPI.java:130)
        at menu.Menu.acessoGarantido(Menu.java:197)
        at menu.Menu.Inicio(Menu.java:96)
        at Main.main(Main.java:12)
```

**Comment by LucasSnatiago** [comment]
O erro foi corrigido no commit 5dbeb69358496a34c593b895d9257a2a2e2f454d!
