### ISSUE TITLE
bug: Hotfix na sobrecrista do banco de dados

### ISSUE THREAD

**Issue by ThiagoHN** [solid-titans/AEDs3#24]
Após alterar uma reposta, ela sobrescreve o conteúdo de si e da proxima:

```
java.io.IOException: Negative seek offset
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:589)
        at crud.Crud.read(Crud.java:95)
        at menu.backend.cruds.RespostasCRUD.achar(RespostasCRUD.java:60)
        at menu.api.RespostasAPI.escolherResposta(RespostasAPI.java:222)
        at menu.api.RespostasAPI.arquivarResposta(RespostasAPI.java:177)
        at menu.api.APIControle.requisicaoEmPerguntas(APIControle.java:181)
        at menu.Menu.navegarPergunta(Menu.java:300)
        at menu.Menu.acessoGarantido(Menu.java:217)
        at menu.Menu.Inicio(Menu.java:104)
        at Main.main(Main.java:75)
Operação terminou com erro!
```
Após esse erro, se o usuário tentar imprimir a lista de todas as respostas para aquela pergunta, o seguinte erro ocorre:

```
java.io.IOException: Negative seek offset
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:589)
        at crud.Crud.read(Crud.java:95)
        at menu.backend.cruds.UsuariosCRUD.achar(UsuariosCRUD.java:75)
        at menu.frontend.RespostasFrontEnd.listarGeral(RespostasFrontEnd.java:67)
        at menu.api.RespostasAPI.listarRespostasDoGeral(RespostasAPI.java:58)
        at menu.api.APIControle.requisicaoEmPerguntas(APIControle.java:159)
        at menu.Menu.navegarPergunta(Menu.java:300)
        at menu.Menu.acessoGarantido(Menu.java:217)
        at menu.Menu.Inicio(Menu.java:104)
        at Main.main(Main.java:75)
Exception in thread "main" java.lang.NullPointerException
        at menu.frontend.RespostasFrontEnd.listarGeral(RespostasFrontEnd.java:67)
        at menu.api.RespostasAPI.listarRespostasDoGeral(RespostasAPI.java:58)
        at menu.api.APIControle.requisicaoEmPerguntas(APIControle.java:159)
        at menu.Menu.navegarPergunta(Menu.java:300)
        at menu.Menu.acessoGarantido(Menu.java:217)
        at menu.Menu.Inicio(Menu.java:104)
        at Main.main(Main.java:75)
```

**Comment by LucasSnatiago** [comment]
Esse bug tá cabuloso, ele fez metástase e foi pra algum outro lugar do código!
