### ISSUE TITLE
Problema ao listar a primeira pergunta ao ter 10 usuarios

### ISSUE THREAD

**Issue by LucasSnatiago** [solid-titans/AEDs3#7]
Tendo 10 usuários ou mais e clicar para listar as perguntas o programa trava dando essa mensagem de erro:

```
java.io.IOException: Negative seek offset
	at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:589)
	at crud.Crud.read(Crud.java:94)
	at menu.sistema.CrudAPI.getPerguntaArray(CrudAPI.java:295)
	at menu.pergunta.PerguntasAPI.listarPerguntas(PerguntasAPI.java:227)
	at menu.sistema.CrudAPI.verificarRequisicaoDoUsuario(CrudAPI.java:120)
	at menu.Menu.acessoGarantido(Menu.java:190)
	at menu.Menu.Inicio(Menu.java:90)
	at Main.main(Main.java:12)
Exception in thread "main" java.lang.NullPointerException
	at menu.pergunta.PerguntasFrontEnd.listarPerguntas(PerguntasFrontEnd.java:32)
	at menu.pergunta.PerguntasAPI.listarPerguntas(PerguntasAPI.java:233)
	at menu.sistema.CrudAPI.verificarRequisicaoDoUsuario(CrudAPI.java:120)
	at menu.Menu.acessoGarantido(Menu.java:190)
	at menu.Menu.Inicio(Menu.java:90)
	at Main.main(Main.java:12)
```

**Comment by GustavoLR548** [comment]
Problema resolvido no #9
